on:
  workflow_call:
  workflow_dispatch:

jobs:
  Secret_Scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Gitleaks from container
        run: |
            docker create --name GL --entrypoint /bin/bash --interactive --volume ${{ github.workspace }}:/src zricethezav/gitleaks 
            docker start GL
            docker exec GL git config --global --add safe.directory '/src'
            docker exec --user $(id -u):$(id -g) GL gitleaks detect --source=/src --verbose -c /src/security/gitleaks/gitleaks.toml --report-path /src/gitleaks-report.json
        continue-on-error: true
        
  retrieve_gitleaksID:
   runs-on: ubuntu-latest
   steps:
   - run: |
        curl -s https://raw.githubusercontent.com/Tech-it-or-live-it-Secure-CICD/centralWorkflows/main/engagementIDs.json > test.json
        echo "ID=$(jq '."${{ github.repository }}".${{ github.ref_name }}.gitleaksID' test.json)"

  post_to_DD:
    runs-on: ubuntu-latest
    steps:
    - run: echo "placeholder for dd action"
