on:
  workflow_call:
  workflow_dispatch:

jobs:

  pass-secret-to-action:
    runs-on: ubuntu-latest
    steps:
    # passing the secret to an action
      - name: Pass the received secret to an action
        run: |
         echo " e ${{ secrets.GH_TOKEN }} this workflow originally belongs to Tech-it-or-live-it-Secure-CICD/centralWorkflows!!!"
         env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
