on:
  workflow_call:
  workflow_dispatch:

jobs:

  retrieve_gitleaksID:
   runs-on: ubuntu-latest
   steps:
   - run: |
        curl -s https://raw.githubusercontent.com/Tech-it-or-live-it-Secure-CICD/centralWorkflows/main/engagementIDs.json > test.json
        echo "ID=$(jq '."${{ github.repository }}".${{ github.ref_name }}.gitleaksID' test.json)"
