on:
  workflow_call:
  workflow_dispatch:
  
jobs:

  retrieve_gitleaksID:
   runs-on: ubuntu-latest
   steps:
   - run: |
        echo "event is: ${{ github.event_name }}   orrr github.event_name "
        echo " github repo_owner is: ${{ github.repository_owner}}     "
        echo " github repo is: ${{ github.repository }}"
        echo " github ref_name is: ${{ github.ref_name }}"
        export ENG=SecretScanning - ${{ github.repository }}-main
        echo "eng is: $ENG"
