name: test IF step
on:
  push:
  workflow_dispatch:

jobs:

  test:
    name: test IF
    runs-on: ubuntu-latest
    steps:
      - name: off minute
        id: set_flag
        run: echo "::set-output name=is_odd_minute::$(($(date +%M) % 2))"
      - name: step1
        if: (steps.set_flag.outputs.is_odd_minute == '1')
        run: echo "this is an odd minute"
      - name: step2
        if: (steps.set_flag.outputs.is_odd_minute == '0' )
        run: echo "this is NOT AN odd minute"
     
